// Golden-corpus helpers shared by the detector suite: the 16 kHz mono s16le
// WAV reader (a port of TuningTests.loadWavSamples) and expected.json
// loading. The corpus lives in tuning/golden/ and is generated by
// tuning/golden/generate.py — the same fixtures the Python and Swift
// suites run.

#pragma once

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <map>
#include <string>
#include <vector>

#include "json.hpp"

// doctest macros (REQUIRE/FAIL) — include "vendor/doctest.h" first.

namespace mynah_test {

struct ExpectedRegion {
    double start = 0.0;
    double end = 0.0;
    bool rejected_by_energy_gate = false;
    // Phase 2 (P2): the min-utterance gate is pinnable now that every
    // implementation applies it to the trimmed buffer — Python measured
    // the padded one, a documented divergence the single engine removes.
    bool rejected_by_min_utterance = false;
};

// The corpus's pinned cases (mirrors the CASES lists in
// tests/test_segmentation_golden.py and TuningTests.swift).
inline constexpr const char* kGoldenCases[] = {
    "quiet_two_utterances",
    "speech_during_calibration",
    "speech_late_in_calibration",
    "noisy_room",
    "click_below_min",
    "trailing_silence_trim",
    "gap_below_silence",
    "speech_over_noise_in_calibration",
    "blip_below_min_utterance",
};

inline std::vector<float> load_wav(const std::filesystem::path& golden_dir,
                                   const std::string& name) {
    std::filesystem::path path = golden_dir / (name + ".wav");
    std::ifstream in(path, std::ios::binary);
    REQUIRE_MESSAGE(in, ("cannot open " + path.string()).c_str());
    std::vector<unsigned char> data((std::istreambuf_iterator<char>(in)),
                                    std::istreambuf_iterator<char>());
    REQUIRE(data.size() >= 12);
    REQUIRE(std::memcmp(data.data(), "RIFF", 4) == 0);
    REQUIRE(std::memcmp(data.data() + 8, "WAVE", 4) == 0);

    std::size_t offset = 12;
    while (offset + 8 <= data.size()) {
        std::string id(reinterpret_cast<const char*>(data.data()) + offset, 4);
        std::size_t size = data[offset + 4] | (data[offset + 5] << 8) |
                           (std::size_t(data[offset + 6]) << 16) |
                           (std::size_t(data[offset + 7]) << 24);
        std::size_t start = offset + 8;
        if (id == "data") {
            std::size_t end = std::min(start + size, data.size());
            std::vector<float> samples;
            samples.reserve((end - start) / 2);
            for (std::size_t i = start; i + 1 < end; i += 2) {
                std::uint16_t raw = data[i] | (data[i + 1] << 8);
                samples.push_back(float(std::int16_t(raw)) / 32768.0f);
            }
            return samples;
        }
        offset = start + size + (size % 2); // chunks are word-aligned
    }
    FAIL("no data chunk");
    return {};
}

inline std::map<std::string, std::vector<ExpectedRegion>> load_expected(
    const std::filesystem::path& golden_dir) {
    std::filesystem::path path = golden_dir / "expected.json";
    std::ifstream in(path, std::ios::binary);
    REQUIRE_MESSAGE(in, ("cannot open " + path.string()).c_str());
    std::string text((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
    json::Value root = json::parse(text);
    REQUIRE(root.is_object());

    std::map<std::string, std::vector<ExpectedRegion>> out;
    for (const auto& [case_name, regions_value] : root.object) {
        REQUIRE_MESSAGE(regions_value.is_array(),
                        ("expected.json: '" + case_name + "' is not an array").c_str());
        std::vector<ExpectedRegion> regions;
        for (const json::Value& region_value : regions_value.array) {
            const json::Value* start = region_value.find("start");
            const json::Value* end = region_value.find("end");
            const json::Value* rejected_energy = region_value.find("rejected_by_energy_gate");
            const json::Value* rejected_min = region_value.find("rejected_by_min_utterance");
            REQUIRE_MESSAGE(start != nullptr,
                            ("expected.json: bad 'start' in " + case_name).c_str());
            REQUIRE_MESSAGE(start->is_number(),
                            ("expected.json: bad 'start' in " + case_name).c_str());
            REQUIRE_MESSAGE(end != nullptr,
                            ("expected.json: bad 'end' in " + case_name).c_str());
            REQUIRE_MESSAGE(end->is_number(),
                            ("expected.json: bad 'end' in " + case_name).c_str());
            REQUIRE_MESSAGE(rejected_energy != nullptr,
                            ("expected.json: bad 'rejected_by_energy_gate' in " +
                             case_name)
                                .c_str());
            REQUIRE_MESSAGE(rejected_energy->is_bool(),
                            ("expected.json: bad 'rejected_by_energy_gate' in " +
                             case_name)
                                .c_str());
            // Required, like the energy verdict: it is part of the pinned
            // contract since P2, and accepting its absence meant a corpus
            // that lost the field would still pass every case.
            REQUIRE_MESSAGE(rejected_min != nullptr,
                            ("expected.json: missing 'rejected_by_min_utterance' in " +
                             case_name)
                                .c_str());
            REQUIRE_MESSAGE(rejected_min->is_bool(),
                            ("expected.json: bad 'rejected_by_min_utterance' in " +
                             case_name)
                                .c_str());
            ExpectedRegion region;
            region.start = start->number;
            region.end = end->number;
            region.rejected_by_energy_gate = rejected_energy->boolean;
            region.rejected_by_min_utterance = rejected_min->boolean;
            regions.push_back(region);
        }
        out[case_name] = std::move(regions);
    }
    return out;
}

} // namespace mynah_test